<a href="https://colab.research.google.com/github/29hashir04/29hashir04/blob/main/Youtube_Niche_DataScrapper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
import pandas as pd
import time

API_KEY = "AIzaSyAMonLvUGGdeHA0a5NCLUaIxzv672j8q9g"

# === Focused Search Terms (India excluded) ===
SEARCH_TERMS = [
    "travel vlog", "travel vlogger", "travel vlogs",
    "solo travel", "couple travel",
    "digital nomad", "travel nomad", "travel nomads", "nomad", "nomads",
    "backpacking travel", "budget travel vlog",
    "van life travel", "road trip vlog",
    "world travel vlog", "adventure travel",
    "travel asia", "travel africa", "travel europe",
    "hidden gems travel", "off the beaten path",
    "street food travel", "food travel vlog",
    "long term travel", "full time traveler"
]

all_creators = {}

print("Starting YouTube search for travel / nomad creators (India excluded)...\n")

for query in SEARCH_TERMS:
    print(f"🔍 Searching: {query}")

    next_page_token = None
    for page in range(4):
        url = "https://www.googleapis.com/youtube/v3/search"
        params = {
            "part": "snippet",
            "q": query,
            "type": "channel",
            "maxResults": 50,
            "order": "relevance",
            "key": API_KEY
        }
        if next_page_token:
            params["pageToken"] = next_page_token

        res = requests.get(url, params=params)

        if res.status_code != 200:
            print(f"  ❌ Error {res.status_code} for '{query}'")
            break

        data = res.json()
        items = data.get("items", [])

        for item in items:
            channel_id = item["snippet"]["channelId"]
            title = item["snippet"]["title"]
            description = item["snippet"].get("description", "")
            custom_url = item["snippet"].get("customUrl")

            # Skip if clearly India-related
            if any(word in (title + description).lower() for word in ["india", "indian", "bharat", "delhi", "mumbai", "bangalore"]):
                continue

            if channel_id not in all_creators:
                all_creators[channel_id] = {
                    "Channel Title": title,
                    "Channel ID": channel_id,
                    "Custom URL": f"https://youtube.com/{custom_url}" if custom_url else f"https://youtube.com/channel/{channel_id}",
                    "Description": description[:250],
                }

        next_page_token = data.get("nextPageToken")
        if not next_page_token:
            break

        time.sleep(0.5)

print(f"\n✅ Found {len(all_creators)} potential travel/nomad channels (after India filter)")

# ====================== FETCH STATISTICS ======================
if all_creators:
    print("Fetching subscriber counts and stats...")
    channel_ids = list(all_creators.keys())

    for i in range(0, len(channel_ids), 50):
        batch = channel_ids[i:i+50]
        url = "https://www.googleapis.com/youtube/v3/channels"
        params = {
            "part": "statistics,snippet",
            "id": ",".join(batch),
            "key": API_KEY
        }

        res = requests.get(url, params=params)

        if res.status_code == 200:
            for item in res.json().get("items", []):
                ch_id = item["id"]
                stats = item.get("statistics", {})
                snippet = item.get("snippet", {})

                title = snippet.get("title", "")
                desc = snippet.get("description", "")

                # Double-check exclusion
                if any(word in (title + desc).lower() for word in ["india", "indian", "bharat", "delhi", "mumbai"]):
                    if ch_id in all_creators:
                        del all_creators[ch_id]
                    continue

                all_creators[ch_id]["Subscribers"] = int(stats.get("subscriberCount", 0))
                all_creators[ch_id]["Total Views"] = int(stats.get("viewCount", 0))
                all_creators[ch_id]["Video Count"] = int(stats.get("videoCount", 0))
        else:
            print(f"  Stats error: {res.status_code}")

        time.sleep(0.7)

    # Create DataFrame
    df = pd.DataFrame(all_creators.values())
    df = df.sort_values(by="Subscribers", ascending=False).reset_index(drop=True)

    print(f"\nTop 15 Travel / Nomad YouTube Channels (India Excluded):")
    display(df[["Channel Title", "Subscribers", "Video Count", "Custom URL"]].head(15))

    # Save file
    filename = "/content/travel_nomad_youtubers_no_india.csv"
    df.to_csv(filename, index=False)
    print(f"\n✅ Saved {len(df)} channels to {filename}")

    from google.colab import files
    files.download(filename)

Starting YouTube search for travel / nomad creators (India excluded)...

🔍 Searching: travel vlog
🔍 Searching: travel vlogger
🔍 Searching: travel vlogs
🔍 Searching: solo travel
🔍 Searching: couple travel
🔍 Searching: digital nomad
🔍 Searching: travel nomad
🔍 Searching: travel nomads
🔍 Searching: nomad
🔍 Searching: nomads
🔍 Searching: backpacking travel
🔍 Searching: budget travel vlog
🔍 Searching: van life travel
🔍 Searching: road trip vlog
🔍 Searching: world travel vlog
🔍 Searching: adventure travel
🔍 Searching: travel asia
🔍 Searching: travel africa
🔍 Searching: travel europe
🔍 Searching: hidden gems travel
🔍 Searching: off the beaten path
🔍 Searching: street food travel
🔍 Searching: food travel vlog
🔍 Searching: long term travel
🔍 Searching: full time traveler

✅ Found 3840 potential travel/nomad channels (after India filter)
Fetching subscriber counts and stats...
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403

Top 15 Travel / Nomad YouTube Channels (India Excluded):

,Channel Title,Subscribers,Video Count,Custom URL
0,Sourav Joshi Vlogs,40200000.0,2385.0,https://youtube.com/channel/UCjvgGbPPn-FgYeguc...
1,Mark Wiens,11700000.0,1600.0,https://youtube.com/channel/UCyEd6QBSgat5kkC6s...
2,Village Food Channel,9150000.0,572.0,https://youtube.com/channel/UCuSD-BXA1p8S3HfE8...
3,Drew Binsky,6900000.0,1258.0,https://youtube.com/channel/UC0Ize0RLIbGdH5x4w...
4,Music Travel Love,6120000.0,117.0,https://youtube.com/channel/UCLxAS02eWvfZK4icR...
5,bald and bankrupt,4520000.0,232.0,https://youtube.com/channel/UCxDZs_ltFFvn0FDHT...
6,Kara and Nate,4440000.0,1045.0,https://youtube.com/channel/UC4ijq8Cg-8zQKx8OH...
7,Dale Philip,3740000.0,1015.0,https://youtube.com/channel/UCKygRpISlqs5TufcT...
8,Araya Vlogs,3580000.0,638.0,https://youtube.com/channel/UCnZWFiZOtbKPWkRVS...
9,J House Vlogs,3540000.0,1925.0,https://youtube.com/channel/UCyjhyJoPHcQRxPLnW...
10,Dhruv Rathee Vlogs,3500000.0,226.0,https://youtube.com/channel/UCjNgqJ_FMLntYVzq7...
11,DancingBacons,3410000.0,843.0,https://youtube.com/channel/UCRFj4Yj1nKhgrT-_8...
12,Itchy Boots,3330000.0,804.0,https://youtube.com/channel/UCEIs9nkveW9WmYtsO...
13,KrisTells Vlogs,2970000.0,204.0,https://youtube.com/channel/UC925y3Dn61A7MBXGZ...
14,LivingBobby,2860000.0,311.0,https://youtube.com/channel/UCJnih3sPUFF4BvAD0...

✅ Saved 3753 channels to /content/travel_nomad_youtubers_no_india.csv

In [ ]:
import requests
import pandas as pd
import time

API_KEY = "AIzaSyDNC6CIjFI1YE7GSUSXdZQ2rHwwMgnQmnM"

# === Clean & Focused Search Terms (No Asia) ===
SEARCH_TERMS = [
    "travel vlog", "travel vlogger",
    "solo travel", "couple travel",
    "digital nomad", "travel nomad", "travel nomads", "nomad", "nomads",
    "backpacking travel", "budget travel vlog",
    "van life travel", "road trip vlog",
    "world travel vlog", "adventure travel",
    "travel africa", "travel europe",
    "hidden gems travel", "off the beaten path",
    "street food travel", "long term travel", "full time traveler"
]

all_creators = {}

print("Starting YouTube search for travel / nomad creators...\n")

for query in SEARCH_TERMS:
    print(f"🔍 Searching: {query}")

    next_page_token = None
    for page in range(3):          # Reduced pages to save quota
        url = "https://www.googleapis.com/youtube/v3/search"
        params = {
            "part": "snippet",
            "q": query,
            "type": "channel",
            "maxResults": 50,
            "order": "relevance",
            "key": API_KEY
        }
        if next_page_token:
            params["pageToken"] = next_page_token

        res = requests.get(url, params=params)

        if res.status_code != 200:
            print(f"  ❌ Error {res.status_code} for '{query}'")
            break

        data = res.json()
        items = data.get("items", [])

        for item in items:
            channel_id = item["snippet"]["channelId"]
            title = item["snippet"]["title"]
            description = item["snippet"].get("description", "")
            custom_url = item["snippet"].get("customUrl")

            if channel_id not in all_creators:
                all_creators[channel_id] = {
                    "Channel Title": title,
                    "Channel ID": channel_id,
                    "Custom URL": f"https://youtube.com/{custom_url}" if custom_url else f"https://youtube.com/channel/{channel_id}",
                    "Description": description[:250],
                }

        next_page_token = data.get("nextPageToken")
        if not next_page_token:
            break

        time.sleep(0.6)

print(f"\n✅ Found {len(all_creators)} potential channels")

# ====================== FETCH STATISTICS ======================
if all_creators:
    print("Fetching subscriber counts and stats...")
    channel_ids = list(all_creators.keys())

    for i in range(0, len(channel_ids), 50):
        batch = channel_ids[i:i+50]
        url = "https://www.googleapis.com/youtube/v3/channels"
        params = {
            "part": "statistics,snippet",
            "id": ",".join(batch),
            "key": API_KEY
        }

        res = requests.get(url, params=params)

        if res.status_code == 200:
            for item in res.json().get("items", []):
                ch_id = item["id"]
                stats = item.get("statistics", {})

                all_creators[ch_id]["Subscribers"] = int(stats.get("subscriberCount", 0))
                all_creators[ch_id]["Total Views"] = int(stats.get("viewCount", 0))
                all_creators[ch_id]["Video Count"] = int(stats.get("videoCount", 0))
        else:
            print(f"  Stats error: {res.status_code}")

        time.sleep(0.7)

    # Create DataFrame
    df = pd.DataFrame(all_creators.values())
    df = df.sort_values(by="Subscribers", ascending=False).reset_index(drop=True)

    print(f"\nTop 15 Travel / Nomad YouTube Channels:")
    display(df[["Channel Title", "Subscribers", "Video Count", "Custom URL"]].head(15))

    # Save & Download
    filename = "/content/travel_nomad_youtubers_no_asia.csv"
    df.to_csv(filename, index=False)
    print(f"\n✅ Saved {len(df)} channels to {filename}")

    from google.colab import files
    files.download(filename)

Starting YouTube search for travel / nomad creators...

🔍 Searching: travel vlog
🔍 Searching: travel vlogger
🔍 Searching: solo travel
🔍 Searching: couple travel
🔍 Searching: digital nomad
🔍 Searching: travel nomad
🔍 Searching: travel nomads
🔍 Searching: nomad
🔍 Searching: nomads
🔍 Searching: backpacking travel
🔍 Searching: budget travel vlog
🔍 Searching: van life travel
🔍 Searching: road trip vlog
🔍 Searching: world travel vlog
🔍 Searching: adventure travel
🔍 Searching: travel africa
🔍 Searching: travel europe
🔍 Searching: hidden gems travel
🔍 Searching: off the beaten path
🔍 Searching: street food travel
🔍 Searching: long term travel
🔍 Searching: full time traveler

✅ Found 2738 potential channels
Fetching subscriber counts and stats...

Top 15 Travel / Nomad YouTube Channels:

,Channel Title,Subscribers,Video Count,Custom URL
0,Best Ever Food Review Show,12000000,904,https://youtube.com/channel/UCcAd5Np7fO8SeejB1...
1,Mark Wiens,11700000,1600,https://youtube.com/channel/UCyEd6QBSgat5kkC6s...
2,Travel Thirsty,8160000,1015,https://youtube.com/channel/UCHKVXtT1YBCYUnnr4...
3,Nomad Kids TV,7400000,1644,https://youtube.com/channel/UC8ha8LPrd1tqvO4tv...
4,Drew Binsky,6900000,1258,https://youtube.com/channel/UC0Ize0RLIbGdH5x4w...
5,Music Travel Love,6120000,117,https://youtube.com/channel/UCLxAS02eWvfZK4icR...
6,The Food Ranger,5940000,403,https://youtube.com/channel/UCiAq_SU0ED1C6vWFM...
7,Jatt Prabhjot,4620000,2196,https://youtube.com/channel/UC_71IGEjSWBjQ-9Ak...
8,bald and bankrupt,4520000,232,https://youtube.com/channel/UCxDZs_ltFFvn0FDHT...
9,Kara and Nate,4440000,1045,https://youtube.com/channel/UC4ijq8Cg-8zQKx8OH...
10,STREET FOOD JOURNEY,4290000,251,https://youtube.com/channel/UCc10FHcTr3QnIVw2B...
11,Mumbiker Nikhil,4010000,3090,https://youtube.com/channel/UCNn6AaHharXIbkRle...
12,Dale Philip,3740000,1015,https://youtube.com/channel/UCKygRpISlqs5TufcT...
13,Jatie Vlogs,3700000,2662,https://youtube.com/channel/UCnM1ay_QoQOpa1N2i...
14,Nomad Kids 3D cartoons,3570000,739,https://youtube.com/channel/UCJnlfjNdHGg5uBPhv...

✅ Saved 2738 channels to /content/travel_nomad_youtubers_no_asia.csv

In [ ]:
import requests
import pandas as pd
import time

API_KEY = "AIzaSyDNC6CIjFI1YE7GSUSXdZQ2rHwwMgnQmnM"

# === ONLY "travel ..." search terms ===
SEARCH_TERMS = [
    "travel vlog",
    "travel vlogger",
    "travel nomad",
    "travel nomads",
    "travel couple",
    "travel solo",
    "travel backpacking",
    "travel budget",
    "travel adventure",
    "travel world",
    "travel europe",
    "travel africa",
    "travel usa",
    "travel uk",
    "travel america",
    "travel vanlife",
    "travel hidden gems",
    "travel long term",
    "travel full time"
]

# Allowed countries: USA, UK, UAE, Azerbaijan
ALLOWED_COUNTRIES = {"US", "GB", "AE", "AZ", None}   # None = country not specified

all_creators = {}

print("Starting YouTube search using only 'travel ...' terms...\n")

for query in SEARCH_TERMS:
    print(f"🔍 Searching: {query}")

    next_page_token = None
    for page in range(3):        # Limited to save quota
        url = "https://www.googleapis.com/youtube/v3/search"
        params = {
            "part": "snippet",
            "q": query,
            "type": "channel",
            "maxResults": 50,
            "order": "relevance",
            "key": API_KEY
        }
        if next_page_token:
            params["pageToken"] = next_page_token

        res = requests.get(url, params=params)

        if res.status_code != 200:
            print(f"  ❌ Error {res.status_code} for '{query}'")
            break

        data = res.json()
        items = data.get("items", [])

        for item in items:
            channel_id = item["snippet"]["channelId"]
            if channel_id not in all_creators:
                all_creators[channel_id] = {
                    "Channel Title": item["snippet"]["title"],
                    "Channel ID": channel_id,
                    "Custom URL": f"https://youtube.com/{item['snippet'].get('customUrl')}"
                                 if item["snippet"].get("customUrl")
                                 else f"https://youtube.com/channel/{channel_id}",
                    "Description": item["snippet"].get("description", "")[:250],
                }

        next_page_token = data.get("nextPageToken")
        if not next_page_token:
            break

        time.sleep(0.6)

print(f"\n✅ Found {len(all_creators)} potential channels")

# ====================== FETCH STATS + COUNTRY FILTER ======================
if all_creators:
    print("Fetching stats & filtering by country (USA, UK, UAE, Azerbaijan)...")
    channel_ids = list(all_creators.keys())

    for i in range(0, len(channel_ids), 50):
        batch = channel_ids[i:i+50]
        url = "https://www.googleapis.com/youtube/v3/channels"
        params = {
            "part": "statistics,snippet",
            "id": ",".join(batch),
            "key": API_KEY
        }

        res = requests.get(url, params=params)

        if res.status_code == 200:
            for item in res.json().get("items", []):
                ch_id = item["id"]
                stats = item.get("statistics", {})
                snippet = item.get("snippet", {})

                country = snippet.get("country")

                # Keep only allowed countries
                if country not in ALLOWED_COUNTRIES:
                    if ch_id in all_creators:
                        del all_creators[ch_id]
                    continue

                all_creators[ch_id]["Subscribers"] = int(stats.get("subscriberCount", 0))
                all_creators[ch_id]["Total Views"] = int(stats.get("viewCount", 0))
                all_creators[ch_id]["Video Count"] = int(stats.get("videoCount", 0))
                all_creators[ch_id]["Country"] = country if country else "Not Set"
        else:
            print(f"  Stats error: {res.status_code}")

        time.sleep(0.7)

    # Create DataFrame
    df = pd.DataFrame(all_creators.values())
    df = df.sort_values(by="Subscribers", ascending=False).reset_index(drop=True)

    print(f"\n✅ Final Result: {len(df)} channels from USA, UK, UAE & Azerbaijan")
    display(df[["Channel Title", "Country", "Subscribers", "Video Count", "Custom URL"]].head(20))

    # Save & Download
    filename = "/content/travel_youtubers_usa_uk_uae.csv"
    df.to_csv(filename, index=False)
    print(f"\n✅ File saved and ready for download: {filename}")

    from google.colab import files
    files.download(filename)

Starting YouTube search using only 'travel ...' terms...

🔍 Searching: travel vlog
🔍 Searching: travel vlogger
🔍 Searching: travel nomad
🔍 Searching: travel nomads
🔍 Searching: travel couple
🔍 Searching: travel solo
🔍 Searching: travel backpacking
🔍 Searching: travel budget
🔍 Searching: travel adventure
🔍 Searching: travel world
🔍 Searching: travel europe
🔍 Searching: travel africa
  ❌ Error 403 for 'travel africa'
🔍 Searching: travel usa
  ❌ Error 403 for 'travel usa'
🔍 Searching: travel uk
  ❌ Error 403 for 'travel uk'
🔍 Searching: travel america
  ❌ Error 403 for 'travel america'
🔍 Searching: travel vanlife
  ❌ Error 403 for 'travel vanlife'
🔍 Searching: travel hidden gems
  ❌ Error 403 for 'travel hidden gems'
🔍 Searching: travel long term
  ❌ Error 403 for 'travel long term'
🔍 Searching: travel full time
  ❌ Error 403 for 'travel full time'

✅ Found 1502 potential channels
Fetching stats & filtering by country (USA, UK, UAE, Azerbaijan)...
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403
  Stats error: 403

✅ Final Result: 1295 channels from USA, UK, UAE & Azerbaijan

,Channel Title,Country,Subscribers,Video Count,Custom URL
0,bald and bankrupt,GB,4520000.0,232.0,https://youtube.com/channel/UCxDZs_ltFFvn0FDHT...
1,Kara and Nate,US,4440000.0,1045.0,https://youtube.com/channel/UC4ijq8Cg-8zQKx8OH...
2,Dale Philip,AE,3740000.0,1015.0,https://youtube.com/channel/UCKygRpISlqs5TufcT...
3,The Endless Adventure,US,648000.0,967.0,https://youtube.com/channel/UCEDrRCC0qRtPd5-sS...
4,The Travel World,US,645000.0,380.0,https://youtube.com/channel/UCorVBcR89wztpz9-d...
5,Sol Life,US,575000.0,153.0,https://youtube.com/channel/UC14-B_3C30cxZGuFJ...
6,Adventure Tube,US,537000.0,1686.0,https://youtube.com/channel/UCdYmlK5tGqxFuSkbL...
7,Ordinary Adventures,US,440000.0,746.0,https://youtube.com/channel/UCZrh7jGCGMnxu5GZ_...
8,Labib Hossain Joy,US,375000.0,38.0,https://youtube.com/channel/UCS21B-VVE7wiQtIBg...
9,Traveling with Kristin,US,297000.0,427.0,https://youtube.com/channel/UCS2ezhBvebMx6BUL-...
10,travel world,Not Set,284000.0,88.0,https://youtube.com/channel/UCqkl7ATmbB15U4j0m...
11,Yahya Khan,US,282000.0,177.0,https://youtube.com/channel/UC3rwiPSjb2MbQvRe_...
12,Nomadic Statik,US,255000.0,1.0,https://youtube.com/channel/UCsgnE460ebvgB1I30...
13,Adventure Elliot,US,250000.0,275.0,https://youtube.com/channel/UCI3k96jv3yMq1EMmU...
14,Adventure Tours Travel,US,233000.0,435.0,https://youtube.com/channel/UCIeVe6Bv-0K42wv91...
15,Retirement Travelers,US,198000.0,299.0,https://youtube.com/channel/UCG_bzbQMfRabBhy5c...
16,Myer Travels,US,190000.0,360.0,https://youtube.com/channel/UCFKiXXD3aVWU60VQC...
17,Being Neiicey,US,187000.0,439.0,https://youtube.com/channel/UCQuRl7ovhvJAORIPO...
18,Riri Travels,GB,167000.0,57.0,https://youtube.com/channel/UCoX3kFWtGcSHTbdQF...
19,Family Traveler அமெரிக்க VLOGS,US,120000.0,924.0,https://youtube.com/channel/UCTk9yzZAXir64WOpX...

✅ File saved and ready for download: /content/travel_youtubers_usa_uk_uae.csv